# Generated by Django 5.0.6 on 2024-06-19 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(default=1, max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='staus',
            field=models.BooleanField(default=True),
        ),
    ]
