# Generated by Django 5.0.6 on 2024-06-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_vendor_options_remove_vendor_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
