# Generated by Django 5.0.6 on 2024-06-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_vendor_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='image',
        ),
    ]
