# Generated by Django 5.0.6 on 2024-06-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_remove_productcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='foodimage')),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('price_before_tax', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('tax', models.CharField(choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.productcategory')),
                ('tax_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.tax')),
            ],
        ),
    ]
