# Generated by Django 5.0.4 on 2024-06-20 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gst_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)])),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staus', models.BooleanField(default=True)),
            ],
        ),
    ]
