# Generated by Django 5.0.4 on 2024-07-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('VAT', 'VAT'), ('GST', 'GST'), ('NO-TAX', 'NO-TAX')], max_length=20)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('payment_terms', models.IntegerField(blank=True, help_text='Number of days, Credit Period', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('place_of_supply', models.CharField(max_length=100)),
                ('purchase_bill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_order_date', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('discount', models.FloatField(blank=True, help_text='in %', null=True)),
                ('tax', models.FloatField()),
                ('amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('payment_status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('PARTIALLY', 'PARTIALLY')], max_length=20)),
                ('shipping_cost', models.FloatField(blank=True, null=True)),
                ('recived_date', models.DateField(auto_now_add=True)),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('VAT', 'VAT'), ('GST', 'GST'), ('NO-TAX', 'NO-TAX')], max_length=20)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField()),
                ('place_of_supply', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('discount', models.FloatField(blank=True, help_text='in %', null=True)),
                ('tax', models.FloatField()),
                ('cess', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('order_status', models.CharField(choices=[('Closed', 'Closed'), ('Active', 'Active'), ('Expired', 'Expired')], max_length=30)),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.vendor')),
            ],
        ),
    ]
