# Generated by Django 5.0.4 on 2024-10-11 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_purchase_purchaseorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='staus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='staus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='foodimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_before_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.CharField(choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], default='Inclusive', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='recived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='cess',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_type',
            field=models.CharField(choices=[('VAT', 'VAT'), ('GST', 'GST'), ('NO-TAX', 'NO-TAX')], default='NO-TAX', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
