# Generated by Django 5.0.4 on 2024-10-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_units_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='discription',
            new_name='description',
        ),
    ]
