# Generated by Django 5.0.6 on 2024-10-14 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_rename_discription_units_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_stock', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms')], default='kg', max_length=10)),
                ('min_stock_level', models.FloatField(default=0)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('last_purchase_amount', models.FloatField(blank=True, default=0, null=True)),
                ('stock_alert', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_order_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('NO-TAX', 'NO-TAX')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('NO-TAX', 'NO-TAX')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.inventorystock'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.inventorystock'),
        ),
    ]
