# Generated by Django 5.0.6 on 2024-10-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_inventorystock_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
