# Generated by Django 5.0.6 on 2024-10-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_alter_inventorystock_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='valid_till',
            field=models.DateField(),
        ),
    ]
