# Generated by Django 5.0.6 on 2024-10-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_alter_purchaseorder_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('kg', 'kilograms')], default='kg', max_length=255),
        ),
    ]
