# Generated by Django 5.0.6 on 2024-10-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_purchaseorder_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('kg', 'kilograms')], default='kg', max_length=255),
        ),
    ]
