# Generated by Django 5.0.6 on 2024-10-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_remove_product_image_product_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='unit_quantity',
            field=models.FloatField(default=0),
        ),
    ]
