# Generated by Django 5.0.6 on 2024-10-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_rename_price_product_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='Number_of_stock',
        ),
    ]
