# Generated by Django 5.0.6 on 2024-10-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_rename_stock_product_number_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
