# Generated by Django 5.0.6 on 2024-10-22 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0020_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash')], default='Cash', max_length=20),
        ),
    ]
