# Generated by Django 5.0.6 on 2024-10-22 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0021_alter_customer_gst_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
