# Generated by Django 5.0.6 on 2024-10-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0024_alter_product_unit_price_alter_product_unit_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Number of days, Credit Period', max_length=255, null=True),
        ),
    ]
