# Generated by Django 5.0.6 on 2024-10-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0025_alter_purchase_payment_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_quantity',
            field=models.FloatField(),
        ),
    ]
