# Generated by Django 5.0.6 on 2024-10-25 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0026_alter_product_unit_price_alter_product_unit_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=64, unique=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='Inventory.product')),
            ],
        ),
    ]
