# Generated by Django 5.0.6 on 2024-11-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0028_alter_customer_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
