# Generated by Django 5.0.6 on 2024-11-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0029_alter_customer_country_alter_customer_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
