# Generated by Django 5.0.6 on 2024-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0030_alter_vendor_country_alter_vendor_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
