# Generated by Django 5.0.6 on 2024-11-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0032_customer_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='photo',
            new_name='customer_photo',
        ),
    ]
