# Generated by Django 5.0.6 on 2024-11-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0035_purchaseorder_save_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='balance_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_item',
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('total_price', models.FloatField(editable=False)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorys', to='Inventory.inventorystock')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bill', to='Inventory.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_item',
            field=models.ManyToManyField(to='Inventory.inventorystock'),
        ),
    ]
