# Generated by Django 5.0.6 on 2024-11-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0036_alter_purchase_amount_alter_purchase_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
