# Generated by Django 5.0.6 on 2024-11-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0037_purchase_purchase_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.FloatField(blank=True, default=0, help_text='in %', null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
