# Generated by Django 5.0.6 on 2024-11-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0038_alter_purchase_discount_alter_purchase_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
