# Generated by Django 5.0.6 on 2024-10-21 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_id', models.CharField(max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=20)),
                ('designation', models.CharField(choices=[('Sales Man', 'Sales Man'), ('Manager', 'Manager'), ('Other', 'Other')], max_length=20)),
                ('date_of_join', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_no', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('month', models.CharField(max_length=20)),
                ('date_of_give', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.staff')),
            ],
        ),
    ]
