# Generated by Django 5.0.6 on 2024-10-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffsalary',
            old_name='date_of_give',
            new_name='date_of_salary',
        ),
    ]
