# Generated by Django 5.0.4 on 2024-07-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_order_payment_status_alter_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status1',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('PARTIALLY', 'PARTIALLY')], default='UNPAID', max_length=20),
        ),
    ]
