# Generated by Django 5.0.4 on 2024-07-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_order_payment_status1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payed_amount',
            field=models.FloatField(default=0),
        ),
    ]
