# Generated by Django 5.0.6 on 2024-10-22 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_date_of_give_staffsalary_date_of_salary'),
        ('POS', '0008_order_save_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.staff'),
        ),
    ]
