# Generated by Django 5.0.6 on 2024-11-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0011_returns_returnorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='returns',
            name='adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returns',
            name='adjustment_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='returns',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
