# Generated by Django 5.0.6 on 2024-11-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0012_returns_adjustment_returns_adjustment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_discount',
            field=models.FloatField(default=0),
        ),
    ]
