# Generated by Django 5.0.6 on 2025-07-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0013_order_bill_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cgst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='igst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='sgst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cgst_amount',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cgst_rate',
            field=models.FloatField(default=9.0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='igst_amount',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='igst_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sgst_amount',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sgst_rate',
            field=models.FloatField(default=9.0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='taxable_amount',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
